### ISSUE TITLE
missing library(CLAMSstrict)

### ISSUE THREAD

**Issue by xicameron** [StaafLab/CLAMS-pan-cancer#2]
Hi @deborahfnoliveira , 

library CLAMSstrict is missing. Not on Cran, github nor bioconductor. Wondering if you can share source code. Or just the gene signature itself. 

thanks

**Comment by deborahfnoliveira** [comment]
Hi @xicameron,

The library was never intended to be included in this repo, the files here are just intended for code transparency on another publication utilizing the predictor. I have reached out to the authors in the original CLAMS publication (https://onlinelibrary.wiley.com/doi/10.1002/ijc.33242), but they said the package is not currently in Bioconductor. Could you please contact the corresponding author in that original publication by email so we can share the R files with you?

Best,

Deborah
